// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHdG1hi85kfYO_Atnvaq9TiS0z7blw54',
    appId: '1:955392476606:web:ae7e7a3e930759374da5ef',
    messagingSenderId: '955392476606',
    projectId: 'fluttertest-2afa6',
    authDomain: 'fluttertest-2afa6.firebaseapp.com',
    storageBucket: 'fluttertest-2afa6.firebasestorage.app',
    measurementId: 'G-NBZ4RP1DEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9ofF5Or6S3GRrTlpIgmcZNVMgTLPzaM',
    appId: '1:955392476606:android:d9e0c50c5fb7d04f4da5ef',
    messagingSenderId: '955392476606',
    projectId: 'fluttertest-2afa6',
    storageBucket: 'fluttertest-2afa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXqoEI5l2HPyUVLgLQuT3trSI_4v66Ruk',
    appId: '1:955392476606:ios:50252dc16a9573d44da5ef',
    messagingSenderId: '955392476606',
    projectId: 'fluttertest-2afa6',
    storageBucket: 'fluttertest-2afa6.firebasestorage.app',
    iosBundleId: 'com.kang.stockMananger1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXqoEI5l2HPyUVLgLQuT3trSI_4v66Ruk',
    appId: '1:955392476606:ios:50252dc16a9573d44da5ef',
    messagingSenderId: '955392476606',
    projectId: 'fluttertest-2afa6',
    storageBucket: 'fluttertest-2afa6.firebasestorage.app',
    iosBundleId: 'com.kang.stockMananger1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJHdG1hi85kfYO_Atnvaq9TiS0z7blw54',
    appId: '1:955392476606:web:c1546f20a1475e914da5ef',
    messagingSenderId: '955392476606',
    projectId: 'fluttertest-2afa6',
    authDomain: 'fluttertest-2afa6.firebaseapp.com',
    storageBucket: 'fluttertest-2afa6.firebasestorage.app',
    measurementId: 'G-44E93WHC6E',
  );
}
